//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 04:41:26 PM IDT 
//


package com.technion.ai.dao;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}AddedPredicates"/>
 *         &lt;element ref="{}DeletedPredicates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "addedPredicates",
    "deletedPredicates"
})
@XmlRootElement(name = "Effect")
public class Effect {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "AddedPredicates", required = true)
    protected AddedPredicates addedPredicates;
    @XmlElement(name = "DeletedPredicates", required = true)
    protected DeletedPredicates deletedPredicates;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the addedPredicates property.
     * 
     * @return
     *     possible object is
     *     {@link AddedPredicates }
     *     
     */
    public AddedPredicates getAddedPredicates() {
        return addedPredicates;
    }

    /**
     * Sets the value of the addedPredicates property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddedPredicates }
     *     
     */
    public void setAddedPredicates(AddedPredicates value) {
        this.addedPredicates = value;
    }

    /**
     * Gets the value of the deletedPredicates property.
     * 
     * @return
     *     possible object is
     *     {@link DeletedPredicates }
     *     
     */
    public DeletedPredicates getDeletedPredicates() {
        return deletedPredicates;
    }

    /**
     * Sets the value of the deletedPredicates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeletedPredicates }
     *     
     */
    public void setDeletedPredicates(DeletedPredicates value) {
        this.deletedPredicates = value;
    }

}
